server:
  compression:
    enabled: true
  servlet:
    context-path: /ead-auth-user
  forward-headers-strategy: framework

spring:
  application:
    name: ead-auth-user-service
  datasource:
    url: ${ead.database.url}
    username: ${ead.database.username}
    password: ${ead.database.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses: ${ead.broker.connection.address}

resilience4j:
  circuitbreaker:
    instances:
      circuitbreaker-instance:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 80